### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Yingz-e** [ksanjeevan/crnn-audio-classification#22]
I don't know why there is this error,
————————————————————
D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\backend\utils.py:64: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  'The interface of "soundfile" backend is planned to change in 0.8.0 to '

  0%|          | 0/311 [00:00<?, ?it/s]
  0%|          | 0/311 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 175, in <module>
    train_main(config, args.resume)
  File "run.py", line 115, in train_main
    trainer.train()
  File "D:\pycharm_work\crnn-audio-classification-master\train\base_trainer.py", line 88, in train
    result = self._train_epoch(epoch)
  File "D:\pycharm_work\crnn-audio-classification-master\train\trainer.py", line 61, in _train_epoch
    for batch_idx, batch in enumerate(_trange):
  File "D:\Anaconda3\envs\CRNN\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'AugmentationTransform._get_dist.<locals>.<lambda>'
D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\backend\utils.py:64: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  'The interface of "soundfile" backend is planned to change in 0.8.0 to '
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by chentao917** [comment]
> I don't know why there is this error, ———————————————————— D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available. warnings.warn('torchaudio C++ extension is not available.') D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\backend\utils.py:64: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to [pytorch/audio#903](https://github.com/pytorch/audio/issues/903) for the detail. 'The interface of "soundfile" backend is planned to change in 0.8.0 to '
> 
> 0%| | 0/311 [00:00<?, ?it/s] 0%| | 0/311 [00:00<?, ?it/s] Traceback (most recent call last): File "run.py", line 175, in train_main(config, args.resume) File "run.py", line 115, in train_main trainer.train() File "D:\pycharm_work\crnn-audio-classification-master\train\base_trainer.py", line 88, in train result = self._train_epoch(epoch) File "D:\pycharm_work\crnn-audio-classification-master\train\trainer.py", line 61, in _train_epoch for batch_idx, batch in enumerate(_trange): File "D:\Anaconda3\envs\CRNN\lib\site-packages\tqdm\std.py", line 1180, in **iter** for obj in iterable: File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 352, in **iter** return self._get_iterator() File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "D:\Anaconda3\envs\CRNN\lib\site-packages\torch\utils\data\dataloader.py", line 801, in **init** w.start() File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\process.py", line 112, in start self._popen = self._Popen(self) File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\context.py", line 223, in _Popen return _default_context.get_context().Process._Popen(process_obj) File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\context.py", line 322, in _Popen return Popen(process_obj) File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\popen_spawn_win32.py", line 89, in **init** reduction.dump(process_obj, to_child) File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) AttributeError: Can't pickle local object 'AugmentationTransform._get_dist..' D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available. warnings.warn('torchaudio C++ extension is not available.') D:\Anaconda3\envs\CRNN\lib\site-packages\torchaudio\backend\utils.py:64: UserWarning: The interface of "soundfile" backend is planned to change in 0.8.0 to match that of "sox_io" backend and the current interface will be removed in 0.9.0. To use the new interface, do `torchaudio.USE_SOUNDFILE_LEGACY_INTERFACE = False` before setting the backend to "soundfile". Please refer to [pytorch/audio#903](https://github.com/pytorch/audio/issues/903) for the detail. 'The interface of "soundfile" backend is planned to change in 0.8.0 to ' Traceback (most recent call last): File "", line 1, in File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\spawn.py", line 105, in spawn_main exitcode = _main(fd) File "D:\Anaconda3\envs\CRNN\lib\multiprocessing\spawn.py", line 115, in _main self = reduction.pickle.load(from_parent) EOFError: Ran out of input

hey , did you solve this problem? how to fix it?
