### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by hoenickf** [ksanjeevan/crnn-audio-classification#3]
Hi, when I try to train the model, I get the following output. Any idea how to handle it?
./run.py train -c config.json --cfg arch.cfg

Compose(
    ProcessChannels(mode=avg)
    AdditiveNoise(prob=0.3, sig=0.001, dist_type=normal)
    RandomCropLength(prob=0.4, sig=0.25, dist_type=half)
    ToTensorAudio()
)
AudioCRNN(
  (spec): MelspectrogramStretch(num_mels=128, fft_length=2048, norm=spec_whiten, stretch_param=[0.4, 0.4])
  (net): ModuleDict(
    (main): Sequential()
  )
)
Trainable parameters: 0
Traceback (most recent call last):
  File "./run.py", line 176, in <module>
    train_main(config, args.resume)
  File "./run.py", line 97, in train_main
    optimizer = getattr(torch.optim, opt_name)(trainable_params, **opt_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/optim/adam.py", line 42, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/optim/optimizer.py", line 46, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

**Comment by mathematiguy** [comment]
I figured this one out. The `.cfg` file included in the repo is `crnn.cfg`, not `arch.cfg`. I'll put through a PR to the readme file to fix this.
