### ISSUE TITLE
I have a problem while I run this project

### ISSUE THREAD

**Issue by jokerpp** [ksanjeevan/crnn-audio-classification#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 176, in <module>
    train_main(config, args.resume)
  File "run.py", line 78, in train_main
    data_manager = getattr(data_module, config['data']['type'])(config['data'])
  File "/tf/soundclassify/crnn-audio-git/data/data_manager.py", line 131, in __init__
    self.metadata_df = self._remove_too_small(metadata_df, 1)
  File "/tf/soundclassify/crnn-audio-git/data/data_manager.py", line 140, in _remove_too_small
    dur_cond = (df['end'] - df['start'])>=min_sec
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'end'

**Comment by ksanjeevan** [comment]
@jokerpp can you confirm that you have the `metadata/UrbanSound8K.csv` file in whatever directory you've specified for the urbansounds dataset?

**Comment by jokerpp** [comment]
root@e9a94d6cdfb6:/tf/soundclassify# cd crnn-audio-git
root@e9a94d6cdfb6:/tf/soundclassify/crnn-audio-git# ls
README.md        Untitled3.ipynb            crnn.cfg                                      eval                result_plots        utils
Untitled.ipynb   UrbanSound8K               crnn_audio_classification_UrbanSound8k.ipynb  my-selfconfig.json  run.py
Untitled1.ipynb  config.json                data                                          myjson.py           torchaudio-contrib
Untitled2.ipynb  crnn-audio-classification  docker                                        net                 train
root@e9a94d6cdfb6:/tf/soundclassify/crnn-audio-git# cd UrbanSound8K
root@e9a94d6cdfb6:/tf/soundclassify/crnn-audio-git/UrbanSound8K# ls
FREESOUNDCREDITS.txt  UrbanSound8K_README.txt  audio  metadata
root@e9a94d6cdfb6:/tf/soundclassify/crnn-audio-git/UrbanSound8K# cd metadata
root@e9a94d6cdfb6:/tf/soundclassify/crnn-audio-git/UrbanSound8K/metadata# ls
UrbanSound8K.csv

**Comment by jokerpp** [comment]
i have metadata/UrbanSound8K.csv file , above is the  directory structure

**Comment by jokerpp** [comment]
![122112](https://user-images.githubusercontent.com/12561116/67743197-eb1b1f00-fa58-11e9-8514-c8e039308c5c.png)
